<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
        <PackageReference Include="ProjectFiles" />
        <PackageReference Include="TUnit" />
        <PackageReference Include="Verify.TUnit" />
        <PackageReference Include="Argon" />
        <PackageReference Include="DiffEngine" />
        <PackageReference Include="EmptyFiles" />
        <PackageReference Include="SimpleInfoName" />
        <PackageReference Include="Verify" />
        <PackageReference Include="MarkdownSnippets.MsBuild" PrivateAssets="all" />
        <ProjectReference Include="..\WinDebloat\WinDebloat.csproj" />
        <PackageReference Include="System.ServiceProcess.ServiceController" />
    </ItemGroup>
</Project>
