global using System.CommandLine;
global using System.CommandLine.Parsing;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Management;
global using System.ServiceProcess;
global using CliWrap;
global using Microsoft.Win32;
global using Serilog;